export type VisitorRole =
  | 'recruiter-backend'
  | 'recruiter-ai'
  | 'recruiter-fullstack'
  | 'recruiter-data'
  | 'recruiter-automation'
  | 'recruiter-frontend'
  | 'recruiter-infrastructure'
  | 'engineer'
  | 'exploring'
